Repository UlugbekAsadov/LMS-OWA, pull requests merged in 2023-08, with the labels that each got.

#1 LMS-10 : Remove Unwanted Code
  src/assets/icons/logo.svg
  src/components/header/header.jsx
  src/components/sidebar/menu.jsx
  src/components/sidebar/sidebar.jsx
  src/components/user/user.jsx
  src/context/theme.context.jsx
  src/pages/auth/login.jsx
  src/styles/css/global.css
  src/styles/scss/core/layouts/_menu-main.scss
  src/utils/mocks/sidebar.mock.js
Labels: enhancement, good first issue

#2 LMS-10 feat: creat a course page
  src/pages/courses/courses-list.jsx
  src/router/router.jsx
  src/utils/mocks/contracts.mock.js
Labels: enhancement, good first issue

#3 LMS-8 feat: contractor page creat
  src/pages/contracts/contracts-type-list.jsx
  src/router/router.jsx
  src/utils/mocks/contracts.mock.js
Labels: enhancement, good first issue

#6 LMS-bugfix bugfix: fix route bugs
  src/main.jsx
  src/pages/auth/login.jsx
  src/pages/components/auth-footer.jsx
  src/router/router.jsx
Labels: bug

#9 LMS-18 impement shartnomalar turi qoshish page
  index.html
  package-lock.json
  package.json
  src/components/loader/loader.jsx
  src/components/page-header/page-header.jsx
  src/pages/basic-contract/basic-contract.jsx
  src/pages/contracts/add-contracts/create-contract.jsx
  src/pages/contracts/add-contracts/element-page/left-page.jsx
  src/pages/contracts/add-contracts/element-page/right-page.jsx
  src/pages/contracts/contracts-type-list.jsx
  src/pages/courses/courses-list.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/pages/error/403-classic.jsx
  src/pages/error/404-classic.jsx
  src/pages/error/500-classic.jsx
  src/pages/future-professions-contract/future-professions-contract.jsx
  src/pages/global-loader/global-loader.jsx
  src/react-query/api.js
  src/react-query/query/hot-categories.query.js
  src/react-query/query/index.js
  src/router/router.jsx
Labels: bug, enhancement, good first issue

#13 LMS-22 implement xodimlar page
  package-lock.json
  package.json
  src/components/modals/basic-conract-modal/user-form.jsx
  src/components/modals/modal-staffe/add-staff.jsx
  src/layout/head/head.layout.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/pages/educational-centers/staffs/staffs-page.jsx
  src/router/router.jsx
  src/utils/mocks/index.js
  src/utils/mocks/user.mock.js
Labels: bug, enhancement, good first issue

#17 LMS-17 integrate backend kurslar page table
  src/pages/contracts/contracts-type-list.jsx
  src/pages/courses/courses-list.jsx
  src/react-query/queries/hot-categories.query.js
  src/react-query/queries/index.js
  src/react-query/query/index.js
Labels: enhancement, good first issue

#16 LMS-21: Implement oquv markarlar qoshish modal
  src/components/modals/add-bootcamps-modal/add-bootcamps-modal.jsx
  src/components/modals/modal-staff-modal/add-staff-modal.jsx
  src/components/modals/modal-staffe/add-staff.jsx
  src/components/page-header/page-header.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/pages/educational-centers/staffs/staffs-page.jsx
  src/router/router.jsx
Labels: good first issue

#21 LMS-27: integrate backend on talim muassasi qoshish modal
  src/components/modals/add-bootcamps-modal/add-bootcamps-modal.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/react-query/mutations/bootcamp.mutation.js
  src/react-query/mutations/index.js
  src/react-query/queries/bank.query.js
  src/react-query/queries/bootcamps.query.js
  src/react-query/queries/index.js
  src/router/router.jsx
  src/utils/enums/error-messages.enum.js
Labels: WIP

#19 LMS-16 feat: add courses modal
  src/components/modals/confirmation-modal/confirmation-modal.jsx
  src/components/modals/courses-modal/add-course-modal.jsx
  src/components/modals/modal-staff-modal/add-staff-modal.jsx
  src/components/modals/modal-staffe/add-staff.jsx
  src/pages/courses/courses-list.jsx
Labels: bug, enhancement, good first issue

#24 LMS-15 integrate backend shartnomalar table
  src/components/modals/confirmation-modal/confirmation-modal.jsx
  src/components/user/user.jsx
  src/pages/contract/contract.jsx
  src/pages/contracts/add-contracts/element-page/left-page.jsx
  src/pages/contracts/add-contracts/element-page/right-page.jsx
  src/pages/contracts/contracts-type-list.jsx
  src/react-query/api.js
  src/react-query/mutations/hot-categories.mutation.js
  src/react-query/mutations/index.js
  src/react-query/queries/contracts.query.js
  src/react-query/queries/hot-categories.query.js
  src/router/router.jsx
  src/utils/enums/user.enum.js
  src/utils/hooks/useSidebarMenu.hook.jsx
  src/utils/mocks/sidebar.mock.js
  src/utils/mocks/user.mock.js
Labels: bug, enhancement, good first issue

#25 LMS-29: Integrated POST, PUT, DELETE methods on bootcamp page
  src/components/button/button.jsx
  src/components/modals/confirmation-modal/confirmation-modal.jsx
  src/components/modals/courses-modal/add-course-modal.jsx
  src/pages/courses/courses-list.jsx
  src/react-query/mutations/courses.mutation.js
  src/react-query/mutations/index.js
  src/router/router.jsx
  src/utils/enums/error-messages.enum.js
  src/utils/hooks/useSidebarMenu.hook.jsx
  src/utils/mocks/sidebar.mock.js
Labels: enhancement, good first issue

#28 LMS-36: integrated backend on bootcamps update
  src/components/modals/add-bootcamps-modal/add-bootcamps-modal.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/react-query/mutations/bootcamp.mutation.js
Labels: enhancement

#29 LMS-34: Errors handled on every api requests
  package-lock.json
  package.json
  src/main.jsx
  src/react-query/api.js
  src/utils/config/index.js
  src/utils/config/toast.config.js
  src/utils/enums/error-messages.enum.js
Labels: bug

#31 LMS-15 fixbug: fix bug
  src/pages/contracts/add-contracts/element-page/left-page.jsx
  src/utils/enums/error-messages.enum.js
Labels: bug

#33 LMS-33 oquv markaz page
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/button/button.jsx
  src/components/modals/add-bootcamps-modal/add-bootcamps-modal.jsx
  src/components/modals/addl-staff-modal/add-staff-modal.jsx
  src/components/modals/basic-conract-modal/course-form.jsx
  src/components/modals/basic-conract-modal/user-form.jsx
  src/components/modals/change-password-modal/change-password-modal.jsx
  src/components/modals/confirmation-modal/confirmation-modal.jsx
  src/components/modals/courses-modal/add-course-modal.jsx
  src/components/modals/modal-staff-modal/add-staff-modal.jsx
  src/components/modals/modal-staffe/add-staff.jsx
  src/components/page-header/page-header.jsx
  src/pages/auth/login.jsx
  src/pages/contract-type/add-contract-type/contract-type-form/contract-type-form.jsx
  src/pages/contract-type/add-contract-type/contract-type-form/contract-type-word-list.jsx
  src/pages/contract-type/add-contract-type/create-contract.jsx
  src/pages/contract-type/contracts-type-list.jsx
  src/pages/contracts/add-contracts/create-contract.jsx
  src/pages/educational-center-about/education-center-staff/education-staff.jsx
  src/pages/educational-center-about/education-information/education-list/education-information-list.jsx
  src/pages/educational-center-about/education-information/educational-information.jsx
  src/pages/educational-centers/education-center-staffs.jsx
  src/pages/educational-centers/educational-centers-page.jsx
  src/pages/educational-centers/staffs/staffs-page.jsx
  src/pages/staffs/staffs-page.jsx
  src/react-query/api.js
  src/react-query/mutations/hot-categories.mutation.js
  src/react-query/mutations/index.js
  src/react-query/mutations/staffs.mutation.js
  src/react-query/queries/contract-types.query.js
  src/react-query/queries/educational.query.js
  src/react-query/queries/index.js
  src/router/router.jsx
  src/utils/enums/error-messages.enum.js
  src/utils/hooks/useSidebarMenu.hook.jsx
  src/utils/mocks/sidebar.mock.js
  src/utils/mocks/user.mock.js
Labels: bug, enhancement, good first issue

#34 LMS-34 bugfix: date fix
  src/pages/contract/contract.jsx
  src/pages/educational-center-about/education-information/education-list/education-information-list.jsx
  src/utils/functions/convert-date.js
Labels: bug, good first issue
